### ISSUE TITLE
Zappa Slack invite isn't working

### ISSUE THREAD

**Issue by souravjamwal77** [zappa/Zappa#1106]
## Zappa's slack inviter is not working

If you visit [slack.zappa.io/](https://slack.zappa.io/) It isn't working anymore.
## Expected Behavior

Whenever a user opens [slack.zappa.io/](https://slack.zappa.io/) It should give them invite to zappa slack channel. 
## Actual Behavior

But at this time it just keeps loading and then fails.
## Possible Fix

Someone in the https://github.com/Miserlou/zappa-slack-inviter needs to look into it and provide a fix. It may be failing because of outdated zappa (==0.23.0 in the repo)
## Steps to Reproduce

1. Visit the  [slack.zappa.io/](https://slack.zappa.io/)
2. This page will keep reloading and then fails

**Comment by javulticat** [comment]
I believe @Miserlou owns/maintains `zappa.io`, so not much we can do there (Rich, if you see this and want to transfer the domain to the current team of community maintainers, DM me on Slack).  As such, I believe we've tried to remove all references to `zappa.io` from this repository, but let me know if that's not the case.

That said, you can currently use https://slackautoinviter.herokuapp.com/ in order to receive an invite to the Zappa Slack channel.  Let us know if you have any issues.  Thanks!

**Comment by souravjamwal77** [comment]
Thanks @javulticat for the invite link. I think we should add this link to zappa invite repo's README. What do you think?

**Comment by javulticat** [comment]
Feel free to open a PR, but https://github.com/Miserlou/zappa-slack-inviter is maintained by @Miserlou, not the [zappa community group](https://github.com/zappa), so we have no control over it, and that repo hasn't seen any activity in nearly 5 years.  Currently, the only one of @Miserlou's repos the [zappa community group](https://github.com/zappa) has taken over maintenance for is the one you're in now (https://github.com/Miserlou/Zappa ➡️ https://github.com/zappa/Zappa).

**Comment by souravjamwal77** [comment]
@javulticat I think we can update the invite link on our README page (https://github.com/zappa/Zappa/blob/master/README.md#sites-using-zappa) and update the invite link there and also on the slack chat icon at the top.

**Comment by monkut** [comment]
It might be confusing, but the zappa-slack-inviter is a project that uses zappa...
I checked the readme, and it looks like the slack invite is set to https://zappateam.slack.com/ which should work.

closing.
