### ISSUE TITLE
Migrate README (documentation) to readthedocs

### ISSUE THREAD

**Issue by monkut** [zappa/Zappa#1150]
## Context

All of Zappa documentation is contained in the README, where the `master` branch is under developement and does not show the current 'release' documentation.

In addition, the current release procedure is not documented and needs to be added.

## Possible Fix

This issue proposes to migrate/update docs to read the docs so the current release documentation is more easily referenced, and documentation potentially easier to maintain.

**Comment by yankeexe** [comment]
Hey @monkut I would love to work on this, but instead of readthedocs, I will suggest using[ MKDocs materia](https://squidfunk.github.io/mkdocs-material/)l, it's really modern and has got [loads of features](https://squidfunk.github.io/mkdocs-material/reference/) which will help in highlighting the concepts in Zappa better.

**Comment by monkut** [comment]
Looks like the readthedocs service supports MkDocs.  I'm more familiar with sphinx, but I'll take a look at mkdocs.

https://docs.readthedocs.io/en/stable/intro/getting-started-with-mkdocs.html

**Comment by yankeexe** [comment]
Sure

**Comment by yankeexe** [comment]
@monkut any updates on this? 🙂
