### ISSUE TITLE
 CVE-2007-4559 impact

### ISSUE THREAD

**Issue by aksharma96** [zappa/Zappa#1178]
Trellix has reported an issue with python tar file module:
https://www.trellix.com/en-us/about/newsroom/stories/research/tarfile-exploiting-the-world.html

and i can see two instances where vulnerable code is referred:https://github.com/zappa/Zappa/search?q=%22extractALL%22
Credits:https://github.com/advanced-threat-research/Creosote

Can you please help me understand the impact and set of action items?
Will Zappa patch this and handle the vulnerable function?

**Comment by monkut** [comment]
I looked into the filing.  It's my understanding that the vulnerability resides in the fact that `tarfile` can be used to define locations with relative paths, such as `../../myfile`, which my then change the system's underlying functionality.

It the zappa case the only file that is the target of `extractall` usage is the file packaged by zappa itself.
Since zappa is presumably packaging the target tar file, I don't see any issues at the moment.

https://github.com/zappa/Zappa/blob/fff5ed8ad2ee071896a94133909adf220a8e47d9/zappa/core.py#L815-L823

If an attacker can create or replace the zappa `package` on s3 you can be affected, but that is a separate security issue.

I may be overlooking something, so any additional comments are welcome.

**Comment by monkut** [comment]
Closing as zappa is not considered impacted.
