### ISSUE TITLE
support for Django websockets/channels/asgi

### ISSUE THREAD

**Issue by mister-rao** [zappa/Zappa#1236]

**Comment by monkut** [comment]
There may be some opportunities to integrate with lambda's websocket configuration, but I don't thing asgi fits the lambda model, since the advantage with asgi is running concurrent functions in the same process/instance.  

Lambda spins a new instance each time executed, so we can't take advantage of asgi.

**Comment by mister-rao** [comment]
Yes, makes sense. I was thinking the same thing. Suppose I'd want to implement a chat/live location server with websockets. Following the lambda behaviour, if there are 100 users using the server for 1 hour, then lambda would spin up 100 instances, and pricing would be calculated based on execution time. 

Rather stay away from lambda for this xD. Thanks for the reply.
