### ISSUE TITLE
[Migrated] SES event support.

### ISSUE THREAD

**Issue by jneves** [zappa/Zappa#718]
Originally from: https://github.com/Miserlou/Zappa/issues/1818 by [youcandanch](https://github.com/youcandanch)

## Description
Lambda has supported SES events as a trigger for quite awhile now, and there's a few folks that have requested this functionality. It's a fairly easy add; the bulk of the code here is around testing the event shape that comes in.

The one caveat here is that when AWS sends an SES message along, it _doesn't_ send the content of the email, even if the event type is that an email was received. If you're looking for SES support when it comes to _actually handling the content of received emails_, you'll have to set up a [SES to S3 pipeline](https://aws.amazon.com/getting-started/projects/setup-email-receiving-pipeline/) and instead trigger off of an S3 event.

## GitHub Issues
https://github.com/Miserlou/Zappa/issues/1501

**Comment by siran** [comment]
Being able to configure Zappa settings to trigger of an SES event, rather than doing it manually on the console would be indeed nice.

It is not enough to set it to trigger from S3, since you need the information coming from SES informing why was the rule triggered as an email.

S3 is a must to be able to process the email content and to backup the email in case of issues.

Please add support.
