### ISSUE TITLE
[Migrated] Upcoming changes in Lambda. Does it affect Zappa?

### ISSUE THREAD

**Issue by jneves** [zappa/Zappa#814]
Originally from: https://github.com/Miserlou/Zappa/issues/1984 by [soymonitus](https://github.com/soymonitus)

https://aws.amazon.com/es/blogs/compute/coming-soon-updated-lambda-states-lifecycle-for-vpc-networking/

I have seen this regarding function creation. Does it affect Zappa?

**Comment by sneha8595** [comment]
I have the same query

Does anyone know if the lambda functions deployed using Zappa face any issues while updating due to the latest states rollout or is already taken care of?

Context:

All AWS CLIs and SDKs have supported monitoring Lambda function states transitions since the original announcement in 2019. Infrastructure as code tools such as AWS CloudFormation, AWS SAM, Serverless Framework, Hashicorp Terraform (>=2.40.0), and Cloud Custodian (>=0.9.14.0) also already support states. Customers using these tools do not need to take any action as part of this, except for one recommended service role policy change for AWS CloudFormation customers (see Updating CloudFormation’s service role below).

However, there are some customers using SDK-based automation workflows or calling Lambda’s service APIs directly, that must update those workflows for this change. To allow time for testing this change, we are rolling it out in a phased model, much like the initial rollout for VPC attached functions. We encourage all customers to take this opportunity to move to the latest SDKs and tools available.


Reference: https://aws.amazon.com/blogs/compute/coming-soon-expansion-of-aws-lambda-states-to-all-functions/

**Comment by monkut** [comment]
There may be ways to improve deployment state management. But as this issue is old, and no related issues have arisen post introduction of the role out `February 1 2022` I'm going to close this issue.
